sgo_systems/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('home/', include(('home.urls', 'home'), namespace='home')),
    path('fornecedores/', include(('fornecedores.urls', 'fornecedores'), namespace='fornecedores')),
    path('admin/', admin.site.urls),
    path('produtos/', include(('produtos.urls', 'produtos'), namespace='produtos')),
    path('categorias/', include('categorias.urls')),  # Não tem namespace, então não precisa
    path('', include('usuarios.urls')),  # Não tem namespace, então não precisa
    path('modelo/', include(('modelo.urls', 'modelo'), namespace='modelo')),
    path('marca/', include(('marca.urls', 'marca'), namespace='marca')),
    path('funcionarios/', include(('funcionarios.urls', 'funcionarios'), namespace='funcionarios')),
    path('clientes/', include(('cliente.urls', 'clientes'), namespace='clientes')),
    path('entrada/', include(('entrada.urls', 'entrada'), namespace='entrada')),
    path('funcao/', include(('funcao.urls', 'funcao'), namespace='funcao')),
    path('venda/', include('vendas.urls')),
]

sgo_systems/home/urls.py
from django.urls import path
from .views import HomeView


app_name = 'home'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

sgo_systems/marca/urls.py
from django.urls import path
from .views import MarcaList, MarcaCreate, MarcaUpdate, MarcaDelete


app_name = 'marca'


urlpatterns = [
   path('cadastrar_marca/', MarcaCreate.as_view(), name='cadastrar_marca'),
   path('', MarcaList.as_view(), name='listar_marcas'),
   path('deletar_marca/<int:pk>', MarcaDelete.as_view(), name='deletar_marca'),
   path('editar_marca/<int:pk>', MarcaUpdate.as_view(), name='editar_marca'),
]

sgo_systems/modelo/urls.py
from django.urls import path
from . import views
from .views import CadastrarModelo, ListarModelos, EditarModelo, DeletarModelo


app_name = 'modelo'


urlpatterns = [
    path('', ListarModelos.as_view(), name='listar_modelos'),
    path('cadastrar_modelo/', CadastrarModelo.as_view(), name='cadastrar_modelo'),
    path('editar_modelo/<int:pk>', EditarModelo.as_view(), name='editar_modelo' ),
    path('deletar_modelo/<int:pk>', DeletarModelo.as_view(), name='deletar_modelo' ),
]

sgo_systems/vendas/urls.py
# vendas/urls.py
from django.urls import path
from .views import VendaCreateView, VendaListView, VendaUpdateView, VendaDeleteView

app_name = 'venda'

urlpatterns = [
    path('', VendaListView.as_view(), name='listar_vendas'),
    path('cadastrar/', VendaCreateView.as_view(), name='cadastrar_venda'),
    path('editar/<int:pk>/', VendaUpdateView.as_view(), name='editar_venda'),
    path('deletar/<int:pk>/', VendaDeleteView.as_view(), name='deletar_venda'),
]

sgo_systems/templates/components/sidebar.html
<!-- templates/components/sidebar.html -->
<div class="sidebar">
    <div class="sidebar-logo">
        <h2>SGO <span>Óptica</span></h2>
        <p>Sistema de Gestão</p>
    </div>
    
    <nav class="sidebar-menu">
        <ul>
            <li><a href="{% url 'home:home' %}"><i class="fas fa-home"></i> Dashboard</a></li>
            
            <!-- Fornecedores -->
            <li>
                <a href="{% url 'fornecedores:fornecedor_list' %}">
                    <i class="fas fa-truck"></i> Fornecedores
                </a>
            </li>
            
            <!-- Produtos -->
            <li>
                <a href="{% url 'produtos:listar_produtos' %}">
                    <i class="fas fa-glasses"></i> Produtos
                </a>
            </li>
            
            <!-- Modelos -->
            <li>
                <a href="{% url 'modelo:listar_modelos' %}">
                    <i class="fas fa-shapes"></i> Modelos
                </a>
            </li>
            
            <!-- Marcas -->
            <li>
                <a href="{% url 'marca:listar_marcas' %}">
                    <i class="fas fa-tags"></i> Marcas
                </a>
            </li>
            
            <!-- Funcionários -->
            <li>
                <a href="{% url 'funcionarios:listar_funcionario' %}">
                    <i class="fas fa-user-tie"></i> Funcionários
                </a>
            </li>
            
            <!-- Clientes -->
            <li>
                <a href="{% url 'clientes:cliente_list' %}">
                    <i class="fas fa-users"></i> Clientes
                </a>
            </li>

            <!-- Entradas -->
            <li>
                <a href="{% url 'entrada:listar_entrada' %}">
                    <i class="fas fa-arrow-down"></i> Entradas
                </a>
            </li>

            <!-- Vendas -->
            <li>
                <a href="{% url 'venda:listar_vendas' %}">
                    <i class="bi bi-receipt-cutoff"></i> Vendas
                </a>
            </li>
        </ul>
    </nav>
</div>